// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mspm.proto

package protos // import "github.com/vatine/mspm/pkg/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetLabelRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Label                []string `protobuf:"bytes,3,rep,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLabelRequest) Reset()         { *m = SetLabelRequest{} }
func (m *SetLabelRequest) String() string { return proto.CompactTextString(m) }
func (*SetLabelRequest) ProtoMessage()    {}
func (*SetLabelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{0}
}
func (m *SetLabelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLabelRequest.Unmarshal(m, b)
}
func (m *SetLabelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLabelRequest.Marshal(b, m, deterministic)
}
func (dst *SetLabelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLabelRequest.Merge(dst, src)
}
func (m *SetLabelRequest) XXX_Size() int {
	return xxx_messageInfo_SetLabelRequest.Size(m)
}
func (m *SetLabelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLabelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLabelRequest proto.InternalMessageInfo

func (m *SetLabelRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *SetLabelRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SetLabelRequest) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

type PackageInformationRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageInformationRequest) Reset()         { *m = PackageInformationRequest{} }
func (m *PackageInformationRequest) String() string { return proto.CompactTextString(m) }
func (*PackageInformationRequest) ProtoMessage()    {}
func (*PackageInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{1}
}
func (m *PackageInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageInformationRequest.Unmarshal(m, b)
}
func (m *PackageInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageInformationRequest.Marshal(b, m, deterministic)
}
func (dst *PackageInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageInformationRequest.Merge(dst, src)
}
func (m *PackageInformationRequest) XXX_Size() int {
	return xxx_messageInfo_PackageInformationRequest.Size(m)
}
func (m *PackageInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackageInformationRequest proto.InternalMessageInfo

func (m *PackageInformationRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type PackageInformation struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Label                []string `protobuf:"bytes,3,rep,name=Label,proto3" json:"Label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageInformation) Reset()         { *m = PackageInformation{} }
func (m *PackageInformation) String() string { return proto.CompactTextString(m) }
func (*PackageInformation) ProtoMessage()    {}
func (*PackageInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{2}
}
func (m *PackageInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageInformation.Unmarshal(m, b)
}
func (m *PackageInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageInformation.Marshal(b, m, deterministic)
}
func (dst *PackageInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageInformation.Merge(dst, src)
}
func (m *PackageInformation) XXX_Size() int {
	return xxx_messageInfo_PackageInformation.Size(m)
}
func (m *PackageInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PackageInformation proto.InternalMessageInfo

func (m *PackageInformation) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *PackageInformation) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PackageInformation) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

type PackageInformationResponse struct {
	PackageData          []*PackageInformation `protobuf:"bytes,1,rep,name=PackageData,proto3" json:"PackageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PackageInformationResponse) Reset()         { *m = PackageInformationResponse{} }
func (m *PackageInformationResponse) String() string { return proto.CompactTextString(m) }
func (*PackageInformationResponse) ProtoMessage()    {}
func (*PackageInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{3}
}
func (m *PackageInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageInformationResponse.Unmarshal(m, b)
}
func (m *PackageInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageInformationResponse.Marshal(b, m, deterministic)
}
func (dst *PackageInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageInformationResponse.Merge(dst, src)
}
func (m *PackageInformationResponse) XXX_Size() int {
	return xxx_messageInfo_PackageInformationResponse.Size(m)
}
func (m *PackageInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PackageInformationResponse proto.InternalMessageInfo

func (m *PackageInformationResponse) GetPackageData() []*PackageInformation {
	if m != nil {
		return m.PackageData
	}
	return nil
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=Group,proto3" json:"Group,omitempty"`
	Mode                 int32    `protobuf:"varint,4,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Contents             []byte   `protobuf:"bytes,5,opt,name=Contents,proto3" json:"Contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{4}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *File) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *File) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *File) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type NewPackage struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	Files                []*File  `protobuf:"bytes,2,rep,name=Files,proto3" json:"Files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPackage) Reset()         { *m = NewPackage{} }
func (m *NewPackage) String() string { return proto.CompactTextString(m) }
func (*NewPackage) ProtoMessage()    {}
func (*NewPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{5}
}
func (m *NewPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPackage.Unmarshal(m, b)
}
func (m *NewPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPackage.Marshal(b, m, deterministic)
}
func (dst *NewPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPackage.Merge(dst, src)
}
func (m *NewPackage) XXX_Size() int {
	return xxx_messageInfo_NewPackage.Size(m)
}
func (m *NewPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPackage.DiscardUnknown(m)
}

var xxx_messageInfo_NewPackage proto.InternalMessageInfo

func (m *NewPackage) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *NewPackage) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type GetPackageRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	Designator           string   `protobuf:"bytes,2,opt,name=Designator,proto3" json:"Designator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackageRequest) Reset()         { *m = GetPackageRequest{} }
func (m *GetPackageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackageRequest) ProtoMessage()    {}
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{6}
}
func (m *GetPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageRequest.Unmarshal(m, b)
}
func (m *GetPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageRequest.Marshal(b, m, deterministic)
}
func (dst *GetPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageRequest.Merge(dst, src)
}
func (m *GetPackageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackageRequest.Size(m)
}
func (m *GetPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageRequest proto.InternalMessageInfo

func (m *GetPackageRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *GetPackageRequest) GetDesignator() string {
	if m != nil {
		return m.Designator
	}
	return ""
}

type GetPackageResponse struct {
	PackageData          *PackageInformation `protobuf:"bytes,1,opt,name=PackageData,proto3" json:"PackageData,omitempty"`
	Data                 []byte              `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPackageResponse) Reset()         { *m = GetPackageResponse{} }
func (m *GetPackageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPackageResponse) ProtoMessage()    {}
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mspm_484a52839256b41d, []int{7}
}
func (m *GetPackageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageResponse.Unmarshal(m, b)
}
func (m *GetPackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageResponse.Marshal(b, m, deterministic)
}
func (dst *GetPackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageResponse.Merge(dst, src)
}
func (m *GetPackageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPackageResponse.Size(m)
}
func (m *GetPackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageResponse proto.InternalMessageInfo

func (m *GetPackageResponse) GetPackageData() *PackageInformation {
	if m != nil {
		return m.PackageData
	}
	return nil
}

func (m *GetPackageResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SetLabelRequest)(nil), "mspm.SetLabelRequest")
	proto.RegisterType((*PackageInformationRequest)(nil), "mspm.PackageInformationRequest")
	proto.RegisterType((*PackageInformation)(nil), "mspm.PackageInformation")
	proto.RegisterType((*PackageInformationResponse)(nil), "mspm.PackageInformationResponse")
	proto.RegisterType((*File)(nil), "mspm.File")
	proto.RegisterType((*NewPackage)(nil), "mspm.NewPackage")
	proto.RegisterType((*GetPackageRequest)(nil), "mspm.GetPackageRequest")
	proto.RegisterType((*GetPackageResponse)(nil), "mspm.GetPackageResponse")
}

func init() { proto.RegisterFile("mspm.proto", fileDescriptor_mspm_484a52839256b41d) }

var fileDescriptor_mspm_484a52839256b41d = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x6e, 0x9a, 0x04, 0xe8, 0x0d, 0x04, 0x58, 0x4c, 0x98, 0x3e, 0x80, 0x31, 0x2f, 0x79, 0x6a,
	0xa4, 0xf1, 0x86, 0x34, 0x24, 0x60, 0x62, 0x42, 0x62, 0x63, 0x0a, 0x1a, 0x42, 0x88, 0x17, 0xb7,
	0xbd, 0x85, 0x68, 0x8d, 0x1d, 0x62, 0x77, 0xfb, 0x47, 0xfc, 0x4e, 0x64, 0x3b, 0x59, 0x23, 0xda,
	0xa0, 0xbc, 0xec, 0xa9, 0x77, 0xe7, 0xfb, 0xee, 0xbe, 0xfb, 0xee, 0x1a, 0x80, 0x52, 0x57, 0xe5,
	0xac, 0xaa, 0x95, 0x51, 0x24, 0xb2, 0x36, 0x5f, 0xc0, 0xc3, 0xaf, 0x68, 0x3e, 0x8b, 0x39, 0xae,
	0x32, 0xfc, 0xbd, 0x46, 0x6d, 0x08, 0x83, 0xbd, 0x33, 0xb1, 0xb8, 0x14, 0x39, 0x9e, 0x8a, 0x12,
	0x69, 0xc0, 0x82, 0x64, 0x92, 0x75, 0x43, 0x84, 0xc2, 0xdd, 0x6f, 0x58, 0xeb, 0x42, 0x49, 0x3a,
	0x76, 0xaf, 0xad, 0x4b, 0x9e, 0x40, 0xec, 0x6a, 0xd1, 0x90, 0x85, 0xc9, 0x24, 0xf3, 0x0e, 0x3f,
	0x84, 0x67, 0x0d, 0xfc, 0x93, 0xbc, 0x50, 0x75, 0x29, 0x4c, 0xa1, 0xe4, 0xe0, 0x76, 0xfc, 0x02,
	0xc8, 0x36, 0xfc, 0x16, 0x68, 0x7e, 0x87, 0xe9, 0x2e, 0x9a, 0xba, 0x52, 0x52, 0x23, 0x79, 0x73,
	0xd3, 0xef, 0x48, 0x18, 0x41, 0x03, 0x16, 0x26, 0x7b, 0x07, 0x74, 0xe6, 0x14, 0xdd, 0x01, 0xeb,
	0x26, 0xf3, 0x2b, 0x88, 0x3e, 0x16, 0x2b, 0x24, 0x04, 0xa2, 0x0e, 0x59, 0x67, 0x5b, 0x2e, 0x5f,
	0xae, 0x25, 0xd6, 0x0d, 0x47, 0xef, 0xd8, 0xe8, 0x71, 0xad, 0xd6, 0x15, 0x0d, 0x7d, 0xd4, 0x39,
	0x16, 0x7f, 0xa2, 0x96, 0x48, 0x23, 0x16, 0x24, 0x71, 0xe6, 0x6c, 0x32, 0x85, 0x7b, 0x1f, 0x94,
	0x34, 0x28, 0x8d, 0xa6, 0x31, 0x0b, 0x92, 0xfb, 0xd9, 0x8d, 0xcf, 0xcf, 0x00, 0x4e, 0xf1, 0xba,
	0x61, 0x32, 0x40, 0x31, 0x06, 0xb1, 0xe5, 0xa9, 0xe9, 0xd8, 0x4d, 0x07, 0x7e, 0x3a, 0x1b, 0xca,
	0xfc, 0x03, 0x3f, 0x87, 0xc7, 0xc7, 0x68, 0x1a, 0xcc, 0xf0, 0x8b, 0x79, 0x0e, 0x70, 0x84, 0xba,
	0xc8, 0xa5, 0x30, 0xaa, 0x9d, 0xb4, 0x13, 0xe1, 0x4b, 0x20, 0xdd, 0xb2, 0x7d, 0x92, 0x07, 0x83,
	0x25, 0xb7, 0x52, 0x39, 0xd0, 0xd8, 0x49, 0xe2, 0xec, 0x83, 0x3f, 0x63, 0x88, 0x4e, 0x74, 0x55,
	0x92, 0xb7, 0x30, 0x69, 0xaf, 0x5e, 0x93, 0x7d, 0x5f, 0xf0, 0x9f, 0xbf, 0xc1, 0xb4, 0xb7, 0x0f,
	0x1f, 0x91, 0x9f, 0xb0, 0xbf, 0xa1, 0xdb, 0x3d, 0xca, 0x17, 0xbd, 0xe4, 0x9a, 0xaa, 0xac, 0x3f,
	0xc1, 0x0f, 0xcd, 0x47, 0xe4, 0x10, 0x1e, 0x9c, 0x57, 0x2b, 0x25, 0x96, 0xed, 0xe2, 0x1e, 0x79,
	0xd0, 0x66, 0x95, 0xff, 0x25, 0xf7, 0x0e, 0x60, 0x43, 0x8e, 0x3c, 0xf5, 0x99, 0x5b, 0x4b, 0x6b,
	0x4b, 0x6c, 0xcb, 0xce, 0x47, 0xef, 0x5f, 0xfd, 0x78, 0x99, 0x17, 0xe6, 0xd7, 0x7a, 0x3e, 0x5b,
	0xa8, 0x32, 0xbd, 0x12, 0xa6, 0x90, 0x98, 0xda, 0xf4, 0xb4, 0xba, 0xcc, 0x53, 0xf7, 0xfd, 0xd0,
	0xf3, 0x3b, 0xee, 0xf7, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0xe1, 0x8a, 0x27, 0x55,
	0x04, 0x00, 0x00,
}
